version: 2
jobs:
  build:
    working_directory: ~/refugies-info
    docker:
      - image: circleci/node:10.13.0
    environment:
      USER: circleci
      TERM: someTerm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm run install:client
      - run:
          name: Run tests
          command: npm run test:unit
      - store_artifacts:
          name: upload-jest-coverage-files
          path: coverage/lcov-report
          destination: unit-coverage
