defaults: &defaults
  working_directory: ~/refugies-info
  docker:
    - image: circleci/node:10-jessie-browsers
  environment:
    TZ: "Europe/Paris"

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: npm run install:server && npm run install:client
      - persist_to_workspace:
          root: ~/refugies-info
          paths:
            - node_modules
            - server/node_modules
            - client/node_modules
  full-unit-test-ada:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ./
      - run: npm run test:unit

workflows:
  version: 2
  test:
    jobs:
      - install
      - full-unit-test-ada:
          requires:
            - install
          filters:
            branches:
              only:
                - master
                - release/backend
                - /hotfix/backend.*/
