version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    docker:
      - image: circleci/node:10-jessie-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run install:server
            - run: npm run install:client
            - persist_to_workspace:
                root: ./
                paths:
                  - node_modules
                  - server/node_modules
                  - client/node_modules
  test-code-quality:
    executor:
      name: node/default
    environment:
      NODE_OPTIONS: --max_old_space_size=8192
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ./
            - run: npm run test:types
            - run: npm run test:lint
            - run: npm run test:unit
workflows:
  build-and-test:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - master-frontend
                - master-backend
                - staging-frontend
                - staging-backend
                - dev
      - test-code-quality:
          requires:
            - install
